Expose the search table and add a default view.
Islandora/islandora_usage_stats pull request #68
Opened 2019-07-05 18:37 UTC by jordandukart

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2454

# What does this Pull Request do?
Exposes the `islandora_usage_stats_top_searches` table to views so it can be used to generate a report.

# What's new?
A view showing the top searches in the repository.

# How should this be tested?
Pull the module and clear your cache/rebuild your menus. Notice there is now a `Islandora Usage Stats Top Searches` option available at `admin/reports/islandora-usage-stats-top-searches`. Clicking it shows a list of search results and the frequency of hits.

# Interested parties
@Islandora/7-x-1-x-committers

2019-07-05 19:24 UTC, bondjimbond commented
I cleared all caches, but I'm having trouble accessing the page... The view works in edit mode, but the actual page (/admin/reports/islandora-usage-stats-top-searches) goes nowhere. Is there something else I need to do to make it available?

2019-07-05 19:42 UTC, bondjimbond reviewed
Works for me, thanks.

One question... I would like to see the search term link out to a search on that term. Would this be desirable generally, or am I an outlier?

2019-07-08 11:19 UTC, jordandukart commented
> Works for me, thanks.
> 
> One question... I would like to see the search term link out to a search on that term. Would this be desirable generally, or am I an outlier?

I think this would be a solid improvement, I'll add it.

2019-07-08 14:04 UTC, bondjimbond requested changes

2019-07-08 14:04 UTC, bondjimbond commented on includes/callbacks.inc
> +  dsm($term);
This should be removed.

2019-07-08 14:04 UTC, bondjimbond commented on views/islandora_usage_stats.views_default.inc
> +  $handler->display->display_options['fields']['term']['alter']['make_link'] = TRUE;
The link isn't showing for me... even after clearing the cache about 90 times.

Am I missing something, or is the code missing something?

2019-07-10 18:43 UTC, BrandonMorr commented
@bondjimbond, Jordan is out on vacation for the next 3 weeks so he won't be able to address any further feedback/issues.

Since I'm unable to make changes to his fork or this pull, I've opened up a new pull request: https://github.com/Islandora/islandora_usage_stats/pull/70 where we can continue the conversation/progress.

Please let me know if there's anything else I can do here, otherwise I think we can close this out.

2019-07-10 20:47 UTC, bryjbrown commented
Should we close this PR since active work is being done in #70?

2019-07-10 20:55 UTC, BrandonMorr commented
@bryjbrown sounds like a good plan to me 👍

2019-07-11 14:26 UTC, closed without merging